
//1 DECLARA TUS ACCIONES
export const TYPES={
    INCREMENTAR:"INCREMEMTAR",
    DECREMENTAR:"DECREMENTAR",
    INCREMENTAR_5:"INCREMENTAR_5",
    DECREMENTAR_5:"DECREMENTAR_5",
    RESET:"RESET"
};
