

//CONTADOR
export   const INCREAMENT="INCREAMENT";
export  const DECREAMENT="DECREAMENT";
export   const RESTORE="RESTORE";
//CART


//CRUD

export const CREATE_DATA= "CREATE_DATA",
READ_ALL_DATA= "READ_ALL_DATA",
DELETE_DATA="DELETE_DATA",
UPDATE_DATA="UPDATE_DATA",
NO_DATA="NO_DATA"